# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitGet < Formula
  desc "Clone git repositories to $HOME/src/github.com/<user>/<repo>"
  homepage ""
  version "1.2.202111112125"

  on_macos do
    url "https://github.com/homburg/git-get/releases/download/v1.2.202111112125/git-get_1.2.202111112125_darwin_all.tar.gz"
    sha256 "dcdd08772b93fc8235f0ef287d55e36a4f8dcc4fddeb8f90451a6e7fac669431"

    def install
      bin.install "git-get"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/homburg/git-get/releases/download/v1.2.202111112125/git-get_1.2.202111112125_linux_armv6.tar.gz"
      sha256 "429246bc44b99f92b8f1cd6f9c8de6abf58d5b2402f85e1a35f52ab384d1f569"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homburg/git-get/releases/download/v1.2.202111112125/git-get_1.2.202111112125_linux_amd64.tar.gz"
      sha256 "765d04a79c33e4c97d3a490c798a14c99c6f92b0a83453816826a9cfbf7aec03"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homburg/git-get/releases/download/v1.2.202111112125/git-get_1.2.202111112125_linux_arm64.tar.gz"
      sha256 "4a07a36f3fe187d30f44e91347f0e70ffead6efe0301bd085590890578405315"

      def install
        bin.install "git-get"
      end
    end
  end

  depends_on "git"
end
