# This file was generated by GoReleaser. DO NOT EDIT.
class Tree < Formula
  desc "Clone git repositories to $HOME/src/github.com/<user>/<repo>"
  homepage ""
  version "1.1.201910072050"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/homburg/tree/releases/download/v1.1.201910072050/tree_1.1.201910072050_darwin_amd64.tar.gz"
    sha256 "9a96da87c27a1bab71bb79b74c5d22246887f0eedea50b7ceab7abe8f2cb8898"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/homburg/tree/releases/download/v1.1.201910072050/tree_1.1.201910072050_linux_amd64.tar.gz"
      sha256 "cf2ead57194b2c2833d68064027fb518e3acfc95e81436e8d9131e89020f81bd"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homburg/tree/releases/download/v1.1.201910072050/tree_1.1.201910072050_linux_arm64.tar.gz"
        sha256 "af2e64345d86be9bd69e144ae24481e37b763150a16f1c4ae4995332f41e813b"
      else
        url "https://github.com/homburg/tree/releases/download/v1.1.201910072050/tree_1.1.201910072050_linux_armv6.tar.gz"
        sha256 "8e87cb2c4820ab3612898dece1634a5f8586c24d34179c4c44f03a9026b502e3"
      end
    end
  end
  
  depends_on "tree"

  def install
    bin.install "tree"
  end
end
