# This file was generated by GoReleaser. DO NOT EDIT.
class Tree < Formula
  desc "Clone git repositories to $HOME/src/github.com/<user>/<repo>"
  homepage ""
  version "1.1.201910072044"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/homburg/tree/releases/download/v1.1.201910072044/tree_1.1.201910072044_darwin_amd64.tar.gz"
    sha256 "06c3af6bbb9bdee3b03b09018853a0bc9350ded38b72bae1dfa2ed69003eb808"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/homburg/tree/releases/download/v1.1.201910072044/tree_1.1.201910072044_linux_amd64.tar.gz"
      sha256 "bdcdf15cc501bd9800805e795f86a72b12639f45f0cfce45cbf4b3761f53545e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homburg/tree/releases/download/v1.1.201910072044/tree_1.1.201910072044_linux_arm64.tar.gz"
        sha256 "72b478240f37cd03e69e9726280aa6a50c3c49de1fb4d5b051d1a124c163369f"
      else
        url "https://github.com/homburg/tree/releases/download/v1.1.201910072044/tree_1.1.201910072044_linux_armv6.tar.gz"
        sha256 "b85f88d2456e4ca196822c14f67f81a108d7e718daa57721c3d8a4a3452ecf2d"
      end
    end
  end
  
  depends_on "tree"

  def install
    bin.install "tree"
  end
end
